service: rsvp

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  apiGateway:
    apiKeys:
      - value: 86000ac1287f675172fa260cd9d25ea3af1ea146b9d07e5742d336107ac5e9e3
        description: Basic API key for clients
    usagePlan:
      quota:
        limit: 300
        period: DAY
      throttle:
        burstLimit: 200
        rateLimit: 100

  stage: prod
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "ses:SendEmail"
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

  environment:
    RESPONSES_TABLE: "${self:service}-responses-${opt:stage, self:provider.stage}"

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: wedding-api.brgr.rocks
    basePath: ""
    stage: ${self:provider.stage}

functions:
  submitResponse:
    handler: handler_response.submitResponse
    description: Submit response
    events:
      - http:
          path: responses/accept
          method: post
          cors: true
          private: true
  submitContactform:
    handler: handler_contactform.submit
    description: Submit contact form
    events:
      - http:
          path: contact
          method: post
          cors: true
          private: true

resources:
  Resources:
    ResponsesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.RESPONSES_TABLE}
